### ISSUE TITLE
how to abort all remote uploads

### ISSUE THREAD

**Issue by qazwsdc** [henrydatei/oboom-tools#3]

**Comment by henrydatei** [comment]
At the moment you have to go to the WebGUI and abort there all uploads manually. I‘ll write a script for that.

**Comment by qazwsdc** [comment]
I have tried this but return 403:
curl -s -d "token=$session,remotes=\"9353267\"" "https://api.oboom.com/1/remote/rm" >> /dev/null

I don't know how to get the upload id.

**Comment by henrydatei** [comment]
The script [restart-uploads.sh](https://github.com/henrydatei/oboom-tools/blob/master/restart-uploads.sh) should give you an idea how to do this.

With
```bash
curl -s -d "token=$session" "https://api.oboom.com/1/remote/lsall" >> upload-state.txt
```
you'll get all information about the uploads,
```bash
id=$(cat upload-state.txt | jq -r ".[3] | .[$i].id")
```
should give you the ID of a specific upload (replace `$I` with a number). Then you could
```bash
curl -s "https://api.oboom.com/1/remote/rm?token=$session&remotes=$id" >> /dev/null
```
with `$session` as the id that is given you when executing `login.sh`

When I have time I'll write a script for doing this automatically.
